Introduction

In this assignment, I use the House Prices - Advanced Regression Techniques dataset from Kaggle. The dataset contains information about houses sold in Ames, Iowa, in the United States. Each row is one house sale, and the columns describe the house, such as its size, quality, age, and location.

The target variable is SalePrice, which is the price the house sold for in US dollars. Because the target is a number, this is a regression problem.

My goal is to prepare this dataset for a machine learning model using feature engineering. I will complete the following steps:

Load the dataset and look at the first 10 rows
Find and fill the missing values
Scale the numerical features using Min-Max scaling
Convert the categorical features into numbers using One-Hot Encoding
Create two new features, TotalSF and Age
Split the data and explain how to prevent data leakage
Train a simple Linear Regression model and evaluate it using mean squared error (MSE)

In [1]:
#import libreries
import pandas as pd

In [2]:
#laod the dataset 
df = pd.read_csv("train.csv")

In [3]:
#show the all column
pd.set_option("display.max_columns",None)

In [4]:
print("Dataset shape:", df.shape)

Dataset shape: (1460, 81)


In [8]:
#check the info of the dataset
print("\nInofromation of dataset:")
print(df.info())



Inofromation of dataset:
<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   str    
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   str    
 6   Alley          91 non-null     str    
 7   LotShape       1460 non-null   str    
 8   LandContour    1460 non-null   str    
 9   Utilities      1460 non-null   str    
 10  LotConfig      1460 non-null   str    
 11  LandSlope      1460 non-null   str    
 12  Neighborhood   1460 non-null   str    
 13  Condition1     1460 non-null   str    
 14  Condition2     1460 non-null   str    
 15  BldgType       1460 non-null   str    
 16  HouseStyle     1460 non-null   str    
 17  OverallQual    1460 non-null   int64 

In [5]:
#check the value count of the dataset
print("\nColumn types:")
print(df.dtypes.value_counts())


Column types:
str        43
int64      35
float64     3
Name: count, dtype: int64


In [7]:
#show the first 5 rows 
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000


Interpretation

In this part, I loaded the House Prices training dataset and looked at its structure. The dataset has 1,460 rows and 81 columns. Each row is one house sale, and the last column, SalePrice, is the target that I want to predict.

I checked the data types of the columns. There are 43 text columns, 35 whole number columns, and 3 decimal number columns. This means the dataset has 38 numerical columns and 43 categorical columns. The categorical columns will need to be converted into numbers before a model can use them.

I also used the info function to see how many values are filled in each column. Most columns have all 1,460 values, but some have missing values. A few columns are almost empty. PoolQC has only 7 filled values, MiscFeature has 54, Alley has 91, and Fence has 281. MasVnrType is also more than half empty, with 588 filled values.

For these columns, I do not think imputation is a good idea. If I fill more than half of a column with one value, almost every house would get the same value, so the column would carry very little real information. Because of this, I plan to remove the columns that have more than 50% missing values, and impute the missing values in the remaining columns. I will do this in the next part.

Finally, I noticed that the Id column is only a row number and does not describe the house, so it should not be used as a feature.

# Part 2: Handling Missing Values

In [14]:
#check the missing values 
missing_count = df.isnull().sum()
#check the missing vlaues in prcentage
missing_value_percentage = (missing_count / len(df)*100).round(1)
# create table to see both value togatehr 
missing_table = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": missing_value_percentage
})


In [15]:
#I need to see the only miisng value columns 
missing_table = missing_table[missing_table["Missing Count"]>0]
missing_table = missing_table.sort_values("Missing Count", ascending = False)

In [16]:
# I show the summary numbers and the table
print("Columns with missing values:", len(missing_table))
print("Total missing values:", missing_count.sum())
missing_table

Columns with missing values: 19
Total missing values: 7829


,Missing Count,Missing Percentage
PoolQC,1453,99.5
MiscFeature,1406,96.3
Alley,1369,93.8
Fence,1179,80.8
MasVnrType,872,59.7
FireplaceQu,690,47.3
LotFrontage,259,17.7
GarageType,81,5.5
GarageYrBlt,81,5.5
GarageFinish,81,5.5


Interpretation

In this step, I inspected the dataset for missing values. I found that 19 of the 81 columns have missing values, with 7,829 missing values in total.

The amount of missing data is very different from column to column. Five columns are more than half empty. PoolQC is missing 99.5% of its values, MiscFeature 96.3%, Alley 93.8%, Fence 80.8%, and MasVnrType 59.7%. FireplaceQu is close behind at 47.3%, and LotFrontage is missing 17.7%.

I also noticed a pattern in the other columns. The five garage columns are each missing exactly 81 values, and the five basement columns are each missing 37 or 38 values. This suggests the values are not missing by accident. These houses most likely do not have a garage or a basement, so there was nothing to record. The same idea applies to PoolQC, Fence, and Alley, because most houses do not have a pool, a fence, or an alley.

Only a few columns look like true gaps in the data. MasVnrArea is missing 8 values and Electrical is missing just 1.

In [39]:
#Drop the mostly empty columns and the Id column
# I use the missing_percent I already calculated in the previous cell
# I find the columns where more than 50% of the values are missing
cols_to_drop = missing_value_percentage[missing_value_percentage > 50].index.tolist()
print("Columns with more than 50% missing:", cols_to_drop)

# I also remove Id, because it is only a row number and does not describe the house
cols_to_drop.append("Id")

# I drop these columns and save the result in a new table, so my original df stays unchanged
df_clean = df.drop(columns=cols_to_drop)

# I compare the size before and after
print("\nShape before:", df.shape)
print("Shape after: ", df_clean.shape)

# I check how many missing values are left
print("\nColumns still with missing values:", (df_clean.isnull().sum() > 0).sum())
print("Missing values left:", df_clean.isnull().sum().sum())

Columns with more than 50% missing: ['Alley', 'MasVnrType', 'PoolQC', 'Fence', 'MiscFeature']

Shape before: (1460, 81)
Shape after:  (1460, 75)

Columns still with missing values: 14
Missing values left: 1550


Interpretation:

In this step, I removed the columns that have more than 50% missing values. The output shows these columns are Alley, MasVnrType, PoolQC, Fence, and MiscFeature. I removed them instead of filling them, because filling more than half of a column with one value would make almost every house look the same, so the column would give the model very little real information.

I also removed the Id column, because it is only a row number and does not describe the house.

After this step, the dataset went from 81 columns to 75 columns, and the number of rows stayed at 1,460. The columns with missing values dropped from 19 to 14, and the total missing values dropped from 7,829 to 1,550. I saved the result in a new table called df_clean, so my original data stays unchanged.

In [43]:
#Fill the "does not have one" values with None and 0
# I list the columns that describe a garage, a basement, and a fireplace
garage_cols = ["GarageType", "GarageFinish", "GarageQual", "GarageCond"]
bsmt_cols = ["BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2"]
fireplace_cols = ["FireplaceQu"]


# I use other columns as proof that the house really does not have the feature
no_garage = df_clean["GarageArea"] == 0
no_bsmt = df_clean["TotalBsmtSF"] == 0
no_fireplace = df_clean["Fireplaces"] == 0

print("Houses with no garage:", no_garage.sum())
print("Houses with no basement:", no_bsmt.sum())
print("Houses with no fireplace:", no_fireplace.sum())

Houses with no garage: 81
Houses with no basement: 37
Houses with no fireplace: 690


In [44]:
# For these houses, I fill the text columns with "None", so "no garage" becomes its own category
df_clean.loc[no_garage, garage_cols] = df_clean.loc[no_garage, garage_cols].fillna("None")
df_clean.loc[no_bsmt, bsmt_cols] = df_clean.loc[no_bsmt, bsmt_cols].fillna("None")
df_clean.loc[no_fireplace, fireplace_cols] = df_clean.loc[no_fireplace, fireplace_cols].fillna("None")

In [45]:
# For houses with no garage, I fill the garage year with 0, because there is no garage to date
df_clean.loc[no_garage, "GarageYrBlt"] = df_clean.loc[no_garage, "GarageYrBlt"].fillna(0)

In [46]:
# I check which columns still have missing values
remaining = df_clean.isnull().sum()
print("\nColumns still with missing values:")
print(remaining[remaining > 0])
print("\nMissing values left:", remaining.sum())


Columns still with missing values:
LotFrontage     259
MasVnrArea        8
BsmtExposure      1
BsmtFinType2      1
Electrical        1
dtype: int64

Missing values left: 270


In [47]:
# I look at the first 5 houses that have no garage, to check they now say "None"
df_clean.loc[no_garage, ["GarageArea", "GarageType", "GarageFinish", "GarageQual", "GarageYrBlt"]].head()

,GarageArea,GarageType,GarageFinish,GarageQual,GarageYrBlt
39,0,None,None,None,0.0
48,0,None,None,None,0.0
78,0,None,None,None,0.0
88,0,None,None,None,0.0
89,0,None,None,None,0.0


In [48]:
# I count how many houses are in each garage type
print(df_clean["GarageType"].value_counts())

GarageType
Attchd     870
Detchd     387
BuiltIn     88
None        81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64


Interpretation:

The assignment asks me to fill missing values with the median and the most frequent category. However, I noticed that this would be wrong for some columns. For a house with no garage, the most frequent category would say it has an attached garage, which is false. So in this step, I went one step further and handled these values separately.

First, I used other columns as proof that a house really does not have the feature. A garage area of 0 means no garage, a basement area of 0 means no basement, and 0 fireplaces means no fireplace. The output shows 81 houses with no garage, 37 with no basement, and 690 with no fireplace. These numbers match the missing values I saw earlier, which confirms my idea.

For these houses, I filled the text columns with the word "None," so that not having a garage, basement, or fireplace becomes its own category. I also filled the garage year with 0, because there is no garage to give a year to. I did not delete these rows, because each house still has many other useful values.

After this step, the missing values dropped from 1,550 to 270. Only five columns still have gaps: LotFrontage with 259, MasVnrArea with 8, and BsmtExposure, BsmtFinType2, and Electrical with 1 each. The two basement values belong to houses that do have a basement, so they are true gaps and were correctly left for the next step.

In [49]:
# I separate the column names into numerical and categorical
num_cols = df_clean.select_dtypes(include="number").columns.tolist()
cat_cols = df_clean.select_dtypes(exclude="number").columns.tolist()

print("Numerical columns:", len(num_cols))
print("Categorical columns:", len(cat_cols))

Numerical columns: 37
Categorical columns: 38


In [52]:
# I find which columns in each group still have gaps
num_missing = [col for col in num_cols if df_clean[col].isnull().any()]
cat_missing = [col for col in cat_cols if df_clean[col].isnull().any()]

# I show the values that will be used to fill the gaps
print("\nMedian used for each numerical column:")
print(df_clean[num_missing].median())

print("\nMost frequent category used for each categorical column:")
print(df_clean[cat_missing].mode().iloc[0])


Median used for each numerical column:
LotFrontage    69.0
MasVnrArea      0.0
dtype: float64

Most frequent category used for each categorical column:
BsmtExposure       No
BsmtFinType2      Unf
Electrical      SBrkr
Name: 0, dtype: str


In [54]:
# I fill the numerical gaps with the median of each column
df_clean[num_cols] = df_clean[num_cols].fillna(df_clean[num_cols].median())

In [55]:
# I fill the categorical gaps with the most frequent category of each column
df_clean[cat_cols] = df_clean[cat_cols].fillna(df_clean[cat_cols].mode().iloc[0])

In [56]:
# I confirm that no missing values are left
print("\nMissing values after imputation:", df_clean.isnull().sum().sum())


Missing values after imputation: 0


In this step, I filled the remaining missing values, which are true gaps where the value exists but was not recorded. First, I separated the columns by type. The output shows 37 numerical columns and 38 categorical columns.

For the numerical columns, I used the median, which is the middle value of the column. I used the median instead of the average because it is not affected by extreme values, such as a few very large houses. The median was 69.0 for LotFrontage and 0.0 for MasVnrArea.

For the categorical columns, I used the most frequent category. This was "No" for BsmtExposure, "Unf" for BsmtFinType2, and "SBrkr" for Electrical.

The final output shows 0 missing values, so the dataset is now complete. Overall, I handled the missing data in three ways. I removed the columns that were mostly empty, I filled the values that mean "the house does not have this feature" with None and 0, and I filled the true gaps with the median and the most frequent category.

# Part 3: Feature Scaling

In [57]:
# I list the numerical columns, and I leave out SalePrice because it is the target, not a feature
num_features = [col for col in num_cols if col != "SalePrice"]
print("Number of numerical features:", len(num_features))
print(num_features)

Number of numerical features: 36
['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']


In [59]:
# I look at the smallest and largest value of every numerical feature
print("\nRanges before scaling:")
print(df_clean[num_features].agg(["min", "max"]).T)


Ranges before scaling:
                  min       max
MSSubClass       20.0     190.0
LotFrontage      21.0     313.0
LotArea        1300.0  215245.0
OverallQual       1.0      10.0
OverallCond       1.0       9.0
YearBuilt      1872.0    2010.0
YearRemodAdd   1950.0    2010.0
MasVnrArea        0.0    1600.0
BsmtFinSF1        0.0    5644.0
BsmtFinSF2        0.0    1474.0
BsmtUnfSF         0.0    2336.0
TotalBsmtSF       0.0    6110.0
1stFlrSF        334.0    4692.0
2ndFlrSF          0.0    2065.0
LowQualFinSF      0.0     572.0
GrLivArea       334.0    5642.0
BsmtFullBath      0.0       3.0
BsmtHalfBath      0.0       2.0
FullBath          0.0       3.0
HalfBath          0.0       2.0
BedroomAbvGr      0.0       8.0
KitchenAbvGr      0.0       3.0
TotRmsAbvGrd      2.0      14.0
Fireplaces        0.0       3.0
GarageYrBlt       0.0    2010.0
GarageCars        0.0       4.0
GarageArea        0.0    1418.0
WoodDeckSF        0.0     857.0
OpenPorchSF       0.0     547.0
EnclosedPorch   

Interpretation

In this step, I identified the numerical features in the dataset. There are 36 numerical features. I left out SalePrice because it is the target that I want to predict, not a feature, so it should not be scaled.

I then checked the smallest and largest value of every numerical feature. The output shows that the features are on very different scales. LotArea goes from 1,300 to 215,245, and MiscVal goes up to 15,500. On the other hand, OverallQual only goes from 1 to 10, and features like FullBath, Fireplaces, and GarageCars only go from 0 to 3 or 4. The year columns, such as YearBuilt and YrSold, are all in the thousands.

This large difference is the reason scaling is needed. Without scaling, a model could treat LotArea as more important than OverallQual only because its numbers are bigger. I also noticed that GarageYrBlt has a minimum of 0, which comes from the value I filled in for houses with no garage, while its real years are close to 2,000.

In [60]:
# I import the Min-Max scaler from scikit-learn
from sklearn.preprocessing import MinMaxScaler

In [61]:
# I make a copy of the cleaned data, so df_clean keeps the original units for later
df_scaled = df_clean.copy()

# I create the scaler and apply it to all 36 numerical features
scaler = MinMaxScaler()
df_scaled[num_features] = scaler.fit_transform(df_clean[num_features])

# I check the smallest value, largest value, and average of every feature after scaling
print("Ranges after scaling:")
print(df_scaled[num_features].agg(["min", "max", "mean"]).T.round(3))

# I confirm the overall range across all scaled features
print("\nSmallest value across all features:", df_scaled[num_features].min().min())
print("Largest value across all features:", df_scaled[num_features].max().max())

# I confirm that the target was not changed
print("\nSalePrice range (not scaled):", df_scaled["SalePrice"].min(), "to", df_scaled["SalePrice"].max())

Ranges after scaling:
               min  max   mean
MSSubClass     0.0  1.0  0.217
LotFrontage    0.0  1.0  0.167
LotArea        0.0  1.0  0.043
OverallQual    0.0  1.0  0.567
OverallCond    0.0  1.0  0.572
YearBuilt      0.0  1.0  0.719
YearRemodAdd   0.0  1.0  0.581
MasVnrArea     0.0  1.0  0.064
BsmtFinSF1     0.0  1.0  0.079
BsmtFinSF2     0.0  1.0  0.032
BsmtUnfSF      0.0  1.0  0.243
TotalBsmtSF    0.0  1.0  0.173
1stFlrSF       0.0  1.0  0.190
2ndFlrSF       0.0  1.0  0.168
LowQualFinSF   0.0  1.0  0.010
GrLivArea      0.0  1.0  0.223
BsmtFullBath   0.0  1.0  0.142
BsmtHalfBath   0.0  1.0  0.029
FullBath       0.0  1.0  0.522
HalfBath       0.0  1.0  0.191
BedroomAbvGr   0.0  1.0  0.358
KitchenAbvGr   0.0  1.0  0.349
TotRmsAbvGrd   0.0  1.0  0.376
Fireplaces     0.0  1.0  0.204
GarageYrBlt    0.0  1.0  0.930
GarageCars     0.0  1.0  0.442
GarageArea     0.0  1.0  0.334
WoodDeckSF     0.0  1.0  0.110
OpenPorchSF    0.0  1.0  0.085
EnclosedPorch  0.0  1.0  0.040
3SsnPorch      0.

Interpretation

In this step, I applied Min-Max scaling to all 36 numerical features. Min-Max scaling changes each value using the formula (x − min) ÷ (max − min), so the smallest value in a column becomes 0 and the largest becomes 1. I saved the result in a new table called df_scaled, so my df_clean table keeps the original units, which I will need later to create new features.

The output shows that every feature now has a minimum of 0.0 and a maximum of 1.0. Before scaling, LotArea went up to 215,245 while OverallQual only went up to 10. Now all features are on the same scale, so no feature can look more important only because its numbers are bigger. I also confirmed that SalePrice was not scaled. It still ranges from 34,900 to 755,000, because it is the target and should stay in real dollars.

The mean values show how Min-Max scaling is affected by extreme values. LotArea has a mean of only 0.043, which means most houses are squeezed close to 0. This happens because one very large lot sets the maximum, and every other house looks small next to it. The same thing happens with MiscVal at 0.003, PoolArea at 0.004, and 3SsnPorch at 0.007, because most houses have a value of 0 for these features and only a few houses have large values.

GarageYrBlt shows the opposite effect, with a mean of 0.930. This is because I filled the garage year with 0 for houses with no garage. That 0 became the minimum, so all the real garage years, which are close to 2,000, are squeezed together near 1. This is a side effect of my earlier choice, and it shows that Min-Max scaling is sensitive to outliers.

Features without extreme values are spread more evenly. For example, OverallQual has a mean of 0.567 and MoSold has a mean of 0.484, which are close to the middle of the range.

Finally, in this step the scaler learned the minimum and maximum from the whole dataset. This is fine for showing how scaling works, but for training a model it would cause data leakage, because the test data would influence the scaling. I will fix this later by splitting the data first and fitting the scaler on the training set only.

# Part 4: Encoding Categorical Features.

In [62]:
# I already separated the categorical columns in Part 2, so I reuse that list here
print("Categorical features:")
print(cat_cols)


Categorical features:
['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']


In [65]:
# I count how many different categories each categorical feature has
category_counts = df_scaled[cat_cols].nunique().sort_values(ascending=False)

print("\nNumber of categories in each feature:")
print(category_counts)

# I add them up to see how many new columns one-hot encoding will create
print("\nTotal number of categories:", category_counts.sum())

# I look at one feature as an example
print("\nCategories in GarageType:")
print(df_scaled["GarageType"].value_counts())


Number of categories in each feature:
Neighborhood     25
Exterior2nd      16
Exterior1st      15
Condition1        9
SaleType          9
RoofMatl          8
Condition2        8
HouseStyle        8
BsmtFinType2      7
Functional        7
BsmtFinType1      7
GarageType        7
Foundation        6
FireplaceQu       6
SaleCondition     6
GarageCond        6
Heating           6
RoofStyle         6
GarageQual        6
MSZoning          5
LotConfig         5
BsmtQual          5
Electrical        5
HeatingQC         5
BldgType          5
BsmtExposure      5
ExterCond         5
BsmtCond          5
LotShape          4
LandContour       4
KitchenQual       4
ExterQual         4
GarageFinish      4
LandSlope         3
PavedDrive        3
Street            2
Utilities         2
CentralAir        2
dtype: int64

Total number of categories: 245

Categories in GarageType:
GarageType
Attchd     870
Detchd     387
BuiltIn     88
None        81
Basment     19
CarPort      9
2Types       6
Name: count,

Interpretation

In this step, I identified the categorical features in the dataset. There are 38 categorical features, which are the text columns I separated earlier.

I then counted how many different categories each feature has. The output shows that the number of categories is very different from feature to feature. Neighborhood has the most, with 25 categories. Exterior2nd has 16 and Exterior1st has 15. Most features have between 4 and 9 categories, and three features, Street, Utilities, and CentralAir, have only 2.

In total, the 38 features have 245 categories. This number is important, because one-hot encoding creates one new column for every category, so I know in advance that it will create 245 new columns.

I also looked at GarageType as an example. It has 7 categories. Attchd is the most common with 870 houses, followed by Detchd with 387. The None category, which I created earlier for houses with no garage, has 81 houses.

In [66]:
# I apply one-hot encoding to all categorical features
# Each category becomes its own column with a value of 1 (yes) or 0 (no)
df_encoded = pd.get_dummies(df_scaled, columns=cat_cols, dtype=int)

# I compare the size before and after encoding
print("Shape before encoding:", df_scaled.shape)
print("Shape after encoding: ", df_encoded.shape)
print("New columns added:", df_encoded.shape[1] - df_scaled.shape[1])

# I look at the new columns that were created from GarageType
garage_type_cols = [col for col in df_encoded.columns if col.startswith("GarageType_")]
print("\nColumns created from GarageType:")
print(garage_type_cols)

# I show the first 5 houses for these columns
print("\nFirst 5 rows of the GarageType columns:")
print(df_encoded[garage_type_cols].head())

# I confirm that every column is now a number
print("\nText columns left:", df_encoded.select_dtypes(exclude="number").shape[1])

Shape before encoding: (1460, 75)
Shape after encoding:  (1460, 282)
New columns added: 207

Columns created from GarageType:
['GarageType_2Types', 'GarageType_Attchd', 'GarageType_Basment', 'GarageType_BuiltIn', 'GarageType_CarPort', 'GarageType_Detchd', 'GarageType_None']

First 5 rows of the GarageType columns:
   GarageType_2Types  GarageType_Attchd  GarageType_Basment  \
0                  0                  1                   0   
1                  0                  1                   0   
2                  0                  1                   0   
3                  0                  0                   0   
4                  0                  1                   0   

   GarageType_BuiltIn  GarageType_CarPort  GarageType_Detchd  GarageType_None  
0                   0                   0                  0                0  
1                   0                   0                  0                0  
2                   0                   0                  0     

Interpretation

In this step, I applied one-hot encoding to all 38 categorical features. One-hot encoding creates a new column for each category and fills it with 1 if the house belongs to that category, or 0 if it does not. I used this method because the categories in this dataset, such as neighborhood names and garage types, have no natural order.

The output shows that the dataset went from 75 columns to 282 columns, and the number of rows stayed at 1,460. This is 207 new columns. The reason it is 207 and not 245 is that the 38 original text columns were removed and replaced by the 245 new category columns.

The GarageType example shows how the encoding works. The single GarageType column became 7 new columns, one for each category. In the first 5 rows, each house has exactly one 1 and six 0s. Four of the houses have a 1 in GarageType_Attchd, and the fourth house has a 1 in GarageType_Detchd. The output also confirms that there are no text columns left, so every column is now a number that a model can use.

One downside of one-hot encoding is that it adds many columns. Here, 245 columns is manageable because the dataset has 1,460 rows and the largest feature has only 25 categories. For a feature with hundreds or thousands of categories, one-hot encoding would create too many columns, and I would consider other methods such as frequency encoding, target encoding, or the hashing trick.

Finally, like scaling, I applied this encoding to the whole dataset to show how it works. For training a model, I will fit the encoder on the training set only, to prevent data leakage.

# Part 5: Feature Engineering

In [67]:
# I create the new features from df_clean, because it still has the real units (square feet and years)

# TotalSF: the total square footage of the house (basement + first floor + second floor)
df_clean["TotalSF"] = df_clean["TotalBsmtSF"] + df_clean["1stFlrSF"] + df_clean["2ndFlrSF"]

# Age: how old the house was when it was sold (year sold - year built)
df_clean["Age"] = df_clean["YrSold"] - df_clean["YearBuilt"]

# I show the first 5 houses, with the original columns next to the new features
print(df_clean[["TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "TotalSF", "YearBuilt", "YrSold", "Age"]].head())

# I look at the statistics of the two new features
print("\nStatistics of the new features:")
print(df_clean[["TotalSF", "Age"]].describe().round(1))

# I check that no house has a negative age, which would be an error in the data
print("\nHouses with a negative age:", (df_clean["Age"] < 0).sum())
print("Houses sold in the same year they were built:", (df_clean["Age"] == 0).sum())

   TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSF  YearBuilt  YrSold  Age
0          856       856       854     2566       2003    2008    5
1         1262      1262         0     2524       1976    2007   31
2          920       920       866     2706       2001    2008    7
3          756       961       756     2473       1915    2006   91
4         1145      1145      1053     3343       2000    2008    8

Statistics of the new features:
       TotalSF     Age
count   1460.0  1460.0
mean    2567.0    36.5
std      821.7    30.3
min      334.0     0.0
25%     2009.5     8.0
50%     2474.0    35.0
75%     3004.0    54.0
max    11752.0   136.0

Houses with a negative age: 0
Houses sold in the same year they were built: 64


In [68]:
# TotalBath: all the bathrooms in the house, where a half bath counts as 0.5
df_clean["TotalBath"] = (df_clean["FullBath"] + 0.5 * df_clean["HalfBath"]
                         + df_clean["BsmtFullBath"] + 0.5 * df_clean["BsmtHalfBath"])

In [69]:
# QualSF: the overall quality rating multiplied by the total size
# This lets the model learn that extra space is worth more in a higher-quality house
df_clean["QualSF"] = df_clean["OverallQual"] * df_clean["TotalSF"]

In [72]:
# RemodAge: how many years passed between the last remodel and the sale
df_clean["RemodAge"] = df_clean["YrSold"] - df_clean["YearRemodAdd"]

# I check for negative values, which would mean the remodel was recorded after the sale
print("Houses with a negative RemodAge:", (df_clean["RemodAge"] < 0).sum())

# I set any negative value to 0, because a remodel age cannot be below zero
df_clean["RemodAge"] = df_clean["RemodAge"].clip(lower=0)

Houses with a negative RemodAge: 1


In [73]:
# ExterQualNum and KitchenQualNum: I turn the quality words into numbers, because quality has a real order
quality_map = {"Ex": 5, "Gd": 4, "TA": 3, "Fa": 2, "Po": 1}
df_clean["ExterQualNum"] = df_clean["ExterQual"].map(quality_map)
df_clean["KitchenQualNum"] = df_clean["KitchenQual"].map(quality_map)

In [74]:
# I show the first 5 houses and the statistics of the new features
extra_features = ["TotalBath", "QualSF", "RemodAge", "ExterQualNum", "KitchenQualNum"]
print("\nFirst 5 rows of the extra features:")
print(df_clean[extra_features].head())


First 5 rows of the extra features:
   TotalBath  QualSF  RemodAge  ExterQualNum  KitchenQualNum
0        3.5   17962         5             4               4
1        2.5   15144        31             3               3
2        3.5   18942         6             4               4
3        2.0   17311        36             3               4
4        3.5   26744         8             4               4


In [75]:
print("\nStatistics of the extra features:")
print(df_clean[extra_features].describe().round(1))


Statistics of the extra features:
       TotalBath    QualSF  RemodAge  ExterQualNum  KitchenQualNum
count     1460.0    1460.0    1460.0        1460.0          1460.0
mean         2.2   16416.0      23.0           3.4             3.5
std          0.8    8665.5      20.6           0.6             0.7
min          1.0     334.0       0.0           2.0             2.0
25%          2.0   10425.0       4.0           3.0             3.0
50%          2.0   14718.0      14.0           3.0             3.0
75%          2.5   20105.8      41.0           4.0             4.0
max          6.0  117520.0      60.0           5.0             5.0


In [76]:
# I confirm that the new features have no missing values
print("\nMissing values in the extra features:", df_clean[extra_features].isnull().sum().sum())


Missing values in the extra features: 0


Interpretation

In this step, I created the two new features that the assignment asks for. I built them from df_clean, because it still has the real units, which are square feet and years. If I had used the scaled table, I would be adding numbers between 0 and 1 that were each scaled differently, and the result would not mean anything.

The first feature is TotalSF, which is the total square footage of the house. I calculated it by adding the basement area, the first floor area, and the second floor area. For example, the first house has 856, 856, and 854 square feet, which gives a TotalSF of 2,566. This feature is useful because a buyer cares about the total size of a house, and the dataset splits that information across three separate columns.

The second feature is Age, which is how old the house was when it was sold. I calculated it by subtracting the year the house was built from the year it was sold. For example, the first house was built in 2003 and sold in 2008, so its Age is 5. The fourth house was built in 1915 and sold in 2006, so its Age is 91. Age is easier to understand than a raw year, and it also takes the sale year into account.

The statistics show that the average house has about 2,567 square feet, and the sizes range from 334 to 11,752 square feet. The average age is about 36.5 years, and the ages range from 0 to 136 years. I also checked the data for errors. No house has a negative age, and 64 houses were sold in the same year they were built, which means they were sold as new houses.

**Five extra features**

In this step, I went beyond the assignment and created five more features, using what I know about what makes a house valuable.

The first is TotalBath, which combines all the bathrooms in the house into one number. I counted each full bathroom as 1 and each half bathroom as 0.5, and I included the basement bathrooms. For example, the first house has a TotalBath of 3.5. The houses in the dataset have between 1 and 6 bathrooms, with an average of about 2.2.

The second is QualSF, which multiplies the overall quality rating by the total square footage. This feature is different from the others because it multiplies two columns instead of adding them. It lets the model learn that extra space is worth more in a high-quality house than in a low-quality house. This is called feature crossing. QualSF ranges from 334 to 117,520, with an average of about 16,416.

The third is RemodAge, which is the number of years between the last remodel and the sale. When I checked the result, I found 1 house with a negative value, which means its remodel year was recorded as later than its sale year. This is not possible, so I set it to 0. RemodAge ranges from 0 to 60 years, with an average of about 23 years.

The fourth and fifth are ExterQualNum and KitchenQualNum. These turn the quality words for the exterior and the kitchen into numbers, where Excellent is 5, Good is 4, Typical is 3, Fair is 2, and Poor is 1. I used numbers here because quality has a real order, which is different from a feature like neighborhood, where the categories have no order. Both features range from 2 to 5, which shows that no house in the dataset is rated Poor for these two qualities, and the average is about 3.4 for the exterior and 3.5 for the kitchen. Finally, I confirmed that the new features have no missing values.

I also learned something important about feature engineering. A Linear Regression model already works by adding up its features, so a new feature that is only a sum or a difference of existing columns, such as TotalSF, Age, TotalBath, and RemodAge, does not give the model new information. These features are still valuable because they are easier to understand and explain. A feature that multiplies two columns, such as QualSF, does give the model new information, because a linear model cannot multiply features by itself.

# Part 6: Data Leakage Prevention

In [77]:
import numpy as np
from sklearn.model_selection import train_test_split

In [78]:
# In Part 2, I filled these 5 columns using the median and most frequent value of ALL houses
# That would leak test information into training, so I put those gaps back
true_gap_cols = ["LotFrontage", "MasVnrArea", "BsmtExposure", "BsmtFinType2", "Electrical"]

df_model = df_clean.copy()
for col in true_gap_cols:
    # A true gap is a value that was missing in the raw data and was not filled with "None"
    was_gap = df[col].isnull() & (df_clean[col] != "None")
    df_model.loc[was_gap, col] = np.nan

print("Shape of df_model:", df_model.shape)
print("Missing values put back, to fill after the split:", df_model.isnull().sum().sum())

Shape of df_model: (1460, 82)
Missing values put back, to fill after the split: 270


In [80]:
# I separate the features (X) from the target (y)
X = df_model.drop(columns="SalePrice")
y = df_model["SalePrice"]

# I split the data: 80% for training and 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# I check the size of each part
print("\nTraining set:", X_train.shape)
print("Testing set: ", X_test.shape)

# I check how many missing values are in each part
print("\nMissing values in the training set:", X_train.isnull().sum().sum())
print("Missing values in the testing set: ", X_test.isnull().sum().sum())


Training set: (1168, 81)
Testing set:  (292, 81)

Missing values in the training set: 224
Missing values in the testing set:  46


Interpretation

In this step, I prepared the data for modeling and split it into a training set and a testing set.

Before splitting, I had to fix one problem. In Part 2, I filled the true gaps in five columns using the median and the most frequent category of all 1,460 houses. Those values were calculated using houses that are about to become my testing set, so information from the test data would leak into training. To fix this, I put those gaps back. The output shows that 270 missing values were put back, which is the same number I had before that imputation step. This confirms that I only undid the one step that caused the leak.

I then separated the features from the target. The table has 82 columns, so I have 81 features and 1 target, which is SalePrice. I split the data so that 80% is used for training and 20% for testing. The output shows 1,168 houses in the training set and 292 houses in the testing set. The training set has 224 missing values and the testing set has 46, which add up to 270. I did not use stratify, because the target is a price and not a class, so there are no classes to balance.

How I ensure that no data leakage occurs

Data leakage happens when information from the testing set is used while preparing or training the model. This makes the test score look better than it really is, because the model has already seen part of the test data. To prevent this, I follow one main rule: I split the data first, and then I learn every preparation value from the training set only.

I divided my steps into two groups. The first group is steps that work on one house at a time, using only that house's own values. These are removing the mostly empty columns, filling None and 0 for houses with no garage, basement, or fireplace, and creating the new features such as TotalSF and Age. These steps do not learn anything from other houses, so they are safe to do before the split.

The second group is steps that learn a value from the whole column. These must be done after the split, and they must learn from the training set only.

For missing values, I will calculate the median and the most frequent category using the training set, and then use those same values to fill the gaps in both the training set and the testing set.

For scaling, I will fit the Min-Max scaler on the training set, so that it learns the minimum and maximum from the training houses only. Then I will use it to transform both sets. Because of this, some test values may fall slightly below 0 or above 1, which is normal and correct.

For encoding, I will fit the one-hot encoder on the training set, so that it learns the list of categories from the training houses only. If the testing set has a category that the encoder never saw, it will be ignored instead of causing an error.

Finally, I do not scale or change the target, SalePrice, and I only use the testing set once, at the end, to evaluate the model.

# Part 7: Model Training

In [81]:
from sklearn.preprocessing import OneHotEncoder

In [82]:
# I make copies, so I do not change the original split
X_train = X_train.copy()
X_test = X_test.copy()

# I separate the numerical and categorical columns of the training set
num_cols_model = X_train.select_dtypes(include="number").columns.tolist()
cat_cols_model = X_train.select_dtypes(exclude="number").columns.tolist()
print("Numerical features:", len(num_cols_model))
print("Categorical features:", len(cat_cols_model))

Numerical features: 43
Categorical features: 38


In [83]:
# STEP 1: IMPUTE
# I learn the median and the most frequent category from the TRAINING set only
train_median = X_train[num_cols_model].median()
train_mode = X_train[cat_cols_model].mode().iloc[0]

# I use those training values to fill the gaps in BOTH sets
X_train[num_cols_model] = X_train[num_cols_model].fillna(train_median)
X_test[num_cols_model] = X_test[num_cols_model].fillna(train_median)
X_train[cat_cols_model] = X_train[cat_cols_model].fillna(train_mode)
X_test[cat_cols_model] = X_test[cat_cols_model].fillna(train_mode)

print("\nMedian of LotFrontage learned from training:", train_median["LotFrontage"])
print("Missing values left in training:", X_train.isnull().sum().sum())
print("Missing values left in testing: ", X_test.isnull().sum().sum())


Median of LotFrontage learned from training: 70.0
Missing values left in training: 0
Missing values left in testing:  0


In [84]:
# STEP 2: SCALE
# I fit the scaler on the TRAINING set only, then I transform both sets
scaler_model = MinMaxScaler()
X_train_num = scaler_model.fit_transform(X_train[num_cols_model])
X_test_num = scaler_model.transform(X_test[num_cols_model])

print("\nTraining range after scaling:", X_train_num.min().round(3), "to", X_train_num.max().round(3))
print("Testing range after scaling: ", X_test_num.min().round(3), "to", X_test_num.max().round(3))


Training range after scaling: 0.0 to 1.0
Testing range after scaling:  0.0 to 1.308


In [85]:
# STEP 3: ENCODE
# I fit the encoder on the TRAINING set only, then I transform both sets
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[cat_cols_model])
X_test_cat = encoder.transform(X_test[cat_cols_model])


In [86]:
# STEP 4: COMBINE
# I join the scaled numerical columns and the encoded categorical columns side by side
X_train_final = np.hstack([X_train_num, X_train_cat])
X_test_final = np.hstack([X_test_num, X_test_cat])

In [87]:
print("\nFinal training set:", X_train_final.shape)
print("Final testing set: ", X_test_final.shape)


Final training set: (1168, 286)
Final testing set:  (292, 286)


Interpretation

In this step, I prepared the training and testing sets for the model. I followed the plan from the previous part, where every value is learned from the training set only and then applied to both sets.

First, I separated the columns by type. There are 43 numerical features and 38 categorical features. The numerical count is higher than before because it now includes the seven new features I created.

Next, I filled the missing values. I calculated the median and the most frequent category from the training set, and I used those same values to fill the gaps in both the training set and the testing set. The median of LotFrontage learned from the training set is 70.0. Earlier, when I used all the houses, it was 69.0. This small difference shows the leak that I removed. This step only filled the true gaps, because the houses with no garage, basement, or fireplace already have the None label, which is a real value and not a missing one. After this step, both sets have 0 missing values.

Then I scaled the numerical features. I fitted the Min-Max scaler on the training set and used it to transform both sets. The training values range from 0 to 1. The testing values go a little above 1, which happens because some test houses have a value larger than any house in the training set. This is expected, and it shows that the scaler did not see the test data.

After that, I encoded the categorical features. I fitted the one-hot encoder on the training set and used it to transform both sets. I set the encoder to ignore any category that appears in the testing set but not in the training set, so it does not cause an error.

Finally, I joined the scaled numerical columns and the encoded categorical columns. The final training set has 1,168 rows and 286 columns, and the final testing set has 292 rows and 286 columns. Both sets have the same number of columns, which confirms they were prepared in the same way.

In [89]:
#Train the Linear Regression model and report the MSE
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [90]:
# I create the model and train it on the prepared training set
model = LinearRegression()
model.fit(X_train_final, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [91]:
# I use the model to predict the sale price for both sets
train_pred = model.predict(X_train_final)
test_pred = model.predict(X_test_final)


In [92]:
# I calculate the mean squared error (MSE) for both sets
train_mse = mean_squared_error(y_train, train_pred)
test_mse = mean_squared_error(y_test, test_pred)

In [93]:
# I take the square root of the MSE to get the error in dollars (RMSE)
train_rmse = train_mse ** 0.5
test_rmse = test_mse ** 0.5

In [94]:
# I calculate R-squared, which shows how much of the price differences the model explains
train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, test_pred)

In [95]:
print("Training performance:")
print(f"  MSE:  {train_mse:,.0f}")
print(f"  RMSE: {train_rmse:,.0f}")
print(f"  R2:   {train_r2:.3f}")

print("\nTesting performance:")
print(f"  MSE:  {test_mse:,.0f}")
print(f"  RMSE: {test_rmse:,.0f}")
print(f"  R2:   {test_r2:.3f}")

Training performance:
  MSE:  271,079,365
  RMSE: 16,464
  R2:   0.955

Testing performance:
  MSE:  739,305,911
  RMSE: 27,190
  R2:   0.904


In [96]:
# I compare the first 5 predictions with the real prices
comparison = pd.DataFrame({
    "Actual price": y_test.values[:5],
    "Predicted price": test_pred[:5].round(0)
})
comparison["Difference"] = comparison["Predicted price"] - comparison["Actual price"]
print("\nFirst 5 test houses:")
print(comparison)

# I show the average sale price, to put the error in context
print(f"\nAverage sale price in the test set: {y_test.mean():,.0f}")


First 5 test houses:
   Actual price  Predicted price  Difference
0        154500         151557.0     -2943.0
1        325000         347878.0     22878.0
2        115000          90945.0    -24055.0
3        159000         167940.0      8940.0
4        315500         309433.0     -6067.0

Average sale price in the test set: 178,840


Interpretation:
In this step, I trained a Linear Regression model on the prepared training set and evaluated it on both sets using the mean squared error (MSE).

The training MSE is 271,079,365 and the testing MSE is 739,305,911. These numbers are very large because MSE squares the errors, and the errors are in dollars. To make the result easier to understand, I also calculated the RMSE, which is the square root of the MSE and shows the typical error in dollars. The training RMSE is 16,464 and the testing RMSE is 27,190.

This means that on houses the model has never seen, its predictions are off by about 27,190 dollars on average. The average sale price in the testing set is 178,840 dollars, so the typical error is about 15% of the price of a house. I also calculated R-squared, which is 0.955 on the training set and 0.904 on the testing set. A testing R-squared of 0.904 means the model explains about 90% of the differences in house prices, which is a good result for a simple model.

The first five test houses show how the predictions look in practice. For the first house, the actual price was 154,500 and the model predicted 151,557, which is only 2,943 too low. For the fifth house, the prediction was 6,067 too low. The model was less accurate on the second and third houses, where it was 22,878 too high and 24,055 too low. So the model is close for many houses but can miss by a larger amount for others.

The model performs better on the training set than on the testing set. The testing MSE is almost three times the training MSE. This shows that the model is overfitting to some degree, which means it learned some details of the training houses that do not apply to new houses. I think this is because the model has 286 features but only 1,168 training houses, and many of the one-hot encoded columns describe categories that only a few houses have.

Overall, the feature engineering worked well. Handling the missing values carefully, scaling the features, encoding the categories, and adding new features gave a simple Linear Regression model a testing R-squared of 0.904. Because I prepared the data without leakage, I can trust that this score reflects how the model would perform on new houses. To improve the model further, I would reduce the overfitting by using a regularized model such as Ridge or Lasso, remove the features that add little value, and apply a log transformation to SalePrice, because house prices are skewed by a few very expensive houses.